---
- name: cache artisan
  become: true
  become_user: "{{ laravel_deploy_user}}"
  command: /usr/bin/php artisan config:cache
  args:
    chdir: "{{ laravel_app_path }}"
  register: artisan_cache_output
  ignore_errors: false
  tags:
    - password

- name: Debug artisan cache output
  debug:
    var: artisan_cache_output
  when: artisan_cache_output is defined
  tags:
    - password
    
- name: reload logrotate
  command: logrotate -f /etc/logrotate.conf
  ignore_errors: true
  become: yes
